# Generated by Django 5.0.6 on 2024-07-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energydata',
            old_name='energy_consumption',
            new_name='power_usage',
        ),
    ]
