# Generated by Django 5.0.6 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_datacenterstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterstatistic',
            name='source',
            field=models.URLField(default='https://datacentremagazine.com/top10/top-10-countries-with-the-most-data-centres'),
        ),
    ]
