# Generated by Django 5.0.6 on 2024-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_datacenterstatistic_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCenterStatistic',
        ),
        migrations.AlterField(
            model_name='article',
            name='table_name',
            field=models.CharField(choices=[('Table 2-4', 'Table 2-4'), ('Table 2-6', 'Table 2-6'), ('Table 2-7', 'Table 2-7'), ('Table 3-2', 'Table 3-2'), ('Table 3-10', 'Table 3-10'), ('Table 6-5', 'Table 6-5'), ('Data Center Statistics', 'Data Center Statistics')], default='Table 2-4', max_length=200),
        ),
    ]
