# Generated by Django 5.0.6 on 2024-08-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
